# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    ignore:
      # Staying on phpunit 9 so we can keep validating against PHP 7
      - dependency-name: "phpunit/phpunit"
        update-types: ["version-update:semver-major"]

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      all-deps:
        patterns:
          - "*"
